"""India (NSE/BSE) market profile — the original Lohi-Trade market."""

from datetime import time

from ..market_profile import (
    BrokerInfo,
    Country,
    Exchange,
    MarketProfile,
    MarketSession,
    NewsSource,
    NumberFormat,
    SettlementCycle,
    TaxProfile,
    TaxRule,
)

INDIA_PROFILE = MarketProfile(
    country=Country.INDIA,
    country_name="India",
    currency="INR",
    currency_symbol="₹",
    timezone="Asia/Kolkata",
    number_format=NumberFormat.INDIAN,
    exchanges=[Exchange.NSE, Exchange.BSE],
    primary_exchange=Exchange.NSE,
    benchmark_index_name="Nifty 50",
    benchmark_symbol="^NSEI",
    benchmark_redis_key="nifty",
    sessions=MarketSession(
        pre_market_start=time(9, 0),
        pre_market_end=time(9, 15),
        market_open=time(9, 15),
        trading_start=time(9, 30),
        trading_end=time(15, 10),
        square_off_time=time(15, 15),
        market_close=time(15, 30),
        post_market_start=time(15, 30),
        post_market_end=time(16, 0),
    ),
    settlement_cycle=SettlementCycle.T1,
    tax_profile=TaxProfile(
        country=Country.INDIA,
        currency="INR",
        transaction_taxes=[
            TaxRule(
                name="STT (Equity Delivery - Sell)",
                rate_pct=0.1,
                applies_to="sell",
                description="Securities Transaction Tax on equity delivery sell side",
            ),
            TaxRule(
                name="STT (Equity Intraday - Sell)",
                rate_pct=0.025,
                applies_to="intraday",
                description="STT on intraday equity sell side",
            ),
            TaxRule(
                name="Exchange Transaction Charges (NSE)",
                rate_pct=0.00345,
                applies_to="both",
                description="NSE transaction charges on turnover",
            ),
            TaxRule(
                name="GST on Brokerage + Transaction Charges",
                rate_pct=18.0,
                applies_to="brokerage",
                description="Goods and Services Tax on brokerage and exchange charges",
            ),
            TaxRule(
                name="Stamp Duty (Buy)",
                rate_pct=0.015,
                applies_to="buy",
                description="Stamp duty charged on buy-side transactions",
            ),
            TaxRule(
                name="SEBI Turnover Fee",
                rate_pct=0.0001,
                applies_to="both",
                description="SEBI regulatory fee on turnover",
            ),
        ],
        capital_gains_short_term_pct=20.0,
        capital_gains_long_term_pct=12.5,
        short_term_threshold_days=365,
        wash_sale_rule=False,
        wash_sale_window_days=0,
        dividend_tax_pct=0.0,  # Taxed at slab rate, not flat
        last_updated="2025-07-01",
        source="manual",
        verified_by_user=True,
        disclaimer=(
            "Tax rates as per Union Budget 2024-25. "
            "Consult a CA for actual tax filing. LTCG exemption up to ₹1.25L/year."
        ),
    ),
    available_brokers=[
        BrokerInfo(
            broker_id="shoonya",
            name="Shoonya (Finvasia)",
            description="Zero-brokerage broker with API access. Good for algo trading.",
            api_type="rest",
            documentation_url="https://shoonya.finvasia.com/api-documentation",
            supports_paper_trading=False,
            supports_options=True,
            supports_futures=True,
            commission_model="zero_commission",
            credential_keys=["SHOONYA_API_KEY", "SHOONYA_CLIENT_ID", "SHOONYA_PASSWORD", "SHOONYA_TOTP_KEY", "SHOONYA_IMEI"],
            validation_patterns={
                "SHOONYA_API_KEY": r"^.{8,}$",
                "SHOONYA_CLIENT_ID": r"^[A-Z0-9]{4,}$",
                "SHOONYA_PASSWORD": r"^.{4,}$",
            },
        ),
        BrokerInfo(
            broker_id="angelone",
            name="Angel One",
            description="Full-service broker with SmartAPI for algorithmic trading.",
            api_type="rest",
            documentation_url="https://smartapi.angelone.in/docs",
            supports_paper_trading=False,
            supports_options=True,
            supports_futures=True,
            commission_model="per_trade",
            credential_keys=["ANGELONE_API_KEY", "ANGELONE_CLIENT_ID", "ANGELONE_PASSWORD", "ANGELONE_TOTP_KEY"],
            validation_patterns={
                "ANGELONE_API_KEY": r"^.{8,}$",
                "ANGELONE_CLIENT_ID": r"^[A-Z0-9]{4,}$",
                "ANGELONE_PASSWORD": r"^.{4,}$",
            },
        ),
        BrokerInfo(
            broker_id="zerodha",
            name="Zerodha (Kite Connect)",
            description="India's largest discount broker. Kite Connect API (₹2000/month).",
            api_type="rest",
            documentation_url="https://kite.trade/docs/connect/v3/",
            supports_paper_trading=False,
            supports_options=True,
            supports_futures=True,
            commission_model="per_trade",
            credential_keys=["ZERODHA_API_KEY", "ZERODHA_API_SECRET", "ZERODHA_USER_ID"],
            validation_patterns={
                "ZERODHA_API_KEY": r"^.{8,}$",
                "ZERODHA_API_SECRET": r"^.{8,}$",
                "ZERODHA_USER_ID": r"^[A-Z]{2}\d{4,}$",
            },
        ),
        BrokerInfo(
            broker_id="groww",
            name="Groww",
            description="Popular investment platform with trading API access.",
            api_type="rest",
            documentation_url="https://groww.in",
            supports_paper_trading=False,
            supports_options=True,
            supports_futures=True,
            commission_model="per_trade",
            credential_keys=["GROWW_API_KEY", "GROWW_CLIENT_ID", "GROWW_PASSWORD"],
            validation_patterns={
                "GROWW_API_KEY": r"^.{8,}$",
                "GROWW_CLIENT_ID": r"^.{4,}$",
                "GROWW_PASSWORD": r"^.{4,}$",
            },
        ),
    ],
    news_sources=[
        NewsSource(name="MoneyControl", url="https://www.moneycontrol.com/rss/latestnews.xml", category="general"),
        NewsSource(name="Economic Times", url="https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms", category="general"),
        NewsSource(name="LiveMint", url="https://www.livemint.com/rss/markets", category="general"),
        NewsSource(name="NSE Announcements", url="https://www.nseindia.com/api/corporate-announcements", category="regulatory"),
        NewsSource(name="BSE Announcements", url="https://www.bseindia.com/corporates/ann.html", category="regulatory"),
    ],
    data_suffix=".NS",
    supports_short_selling=True,
    supports_options=True,
    supports_futures=True,
    supports_pre_market=True,
    supports_after_hours=False,
    min_lot_size=1,
    default_symbols=[
        "RELIANCE", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR",
        "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK", "LT",
        "AXISBANK", "BAJFINANCE", "ASIANPAINT", "MARUTI", "TITAN",
        "SUNPHARMA", "WIPRO", "HCLTECH", "TATAMOTORS", "TATASTEEL",
    ],
    regulator="SEBI (Securities and Exchange Board of India)",
    regulator_url="https://www.sebi.gov.in",
    filing_sources=["bse_feed", "nse_feed", "sebi_edifar"],
)
