"""United States (NYSE/NASDAQ) market profile."""

from datetime import time

from ..market_profile import (
    BrokerInfo,
    Country,
    Exchange,
    MarketProfile,
    MarketSession,
    NewsSource,
    NumberFormat,
    SettlementCycle,
    TaxProfile,
    TaxRule,
)

US_PROFILE = MarketProfile(
    country=Country.UNITED_STATES,
    country_name="United States",
    currency="USD",
    currency_symbol="$",
    timezone="America/New_York",
    number_format=NumberFormat.INTERNATIONAL,
    exchanges=[Exchange.NYSE, Exchange.NASDAQ],
    primary_exchange=Exchange.NYSE,
    benchmark_index_name="S&P 500",
    benchmark_symbol="^GSPC",
    benchmark_redis_key="sp500",
    sessions=MarketSession(
        pre_market_start=time(4, 0),
        pre_market_end=time(9, 30),
        market_open=time(9, 30),
        trading_start=time(9, 45),
        trading_end=time(15, 45),
        square_off_time=time(15, 50),
        market_close=time(16, 0),
        post_market_start=time(16, 0),
        post_market_end=time(20, 0),
    ),
    settlement_cycle=SettlementCycle.T1,
    tax_profile=TaxProfile(
        country=Country.UNITED_STATES,
        currency="USD",
        transaction_taxes=[
            TaxRule(
                name="SEC Fee",
                rate_pct=0.000278,
                applies_to="sell",
                description="SEC regulatory fee on sell-side equity transactions",
            ),
            TaxRule(
                name="TAF (Trading Activity Fee)",
                rate_pct=0.0,
                applies_to="sell",
                description="FINRA Trading Activity Fee ($0.000166 per share, capped at $8.30)",
                is_flat_fee=False,
            ),
            TaxRule(
                name="FINRA Regulatory Fee",
                rate_pct=0.0,
                applies_to="sell",
                description="FINRA fee on sell transactions (minimal)",
                is_flat_fee=True,
                flat_fee_amount=0.01,
            ),
        ],
        capital_gains_short_term_pct=37.0,  # Taxed as ordinary income (top bracket)
        capital_gains_long_term_pct=20.0,  # Top bracket LTCG
        short_term_threshold_days=365,
        wash_sale_rule=True,
        wash_sale_window_days=30,
        dividend_tax_pct=20.0,  # Qualified dividends top rate
        last_updated="2025-01-01",
        source="manual",
        verified_by_user=True,
        disclaimer=(
            "US tax rates vary by income bracket. Short-term gains taxed as ordinary income. "
            "Wash sale rule: cannot claim loss if same security repurchased within 30 days. "
            "Consult a CPA for actual tax filing."
        ),
    ),
    available_brokers=[
        BrokerInfo(
            broker_id="alpaca",
            name="Alpaca",
            description="Commission-free trading API. Excellent for algo trading with paper trading support.",
            api_type="rest",
            documentation_url="https://docs.alpaca.markets",
            supports_paper_trading=True,
            supports_options=True,
            supports_futures=False,
            commission_model="zero_commission",
            credential_keys=["ALPACA_API_KEY", "ALPACA_SECRET_KEY"],
            validation_patterns={
                "ALPACA_API_KEY": r"^(PK|AK)[A-Z0-9]{18,}$",
                "ALPACA_SECRET_KEY": r"^[A-Za-z0-9/+=]{30,}$",
            },
        ),
        BrokerInfo(
            broker_id="interactive_brokers",
            name="Interactive Brokers",
            description="Professional-grade broker with global market access. TWS API or Client Portal.",
            api_type="rest",
            documentation_url="https://interactivebrokers.github.io/cpwebapi/",
            supports_paper_trading=True,
            supports_options=True,
            supports_futures=True,
            commission_model="per_share",
            credential_keys=["IB_ACCOUNT_ID", "IB_USERNAME", "IB_PASSWORD"],
            validation_patterns={
                "IB_ACCOUNT_ID": r"^[A-Z0-9]{4,}$",
                "IB_USERNAME": r"^.{3,}$",
                "IB_PASSWORD": r"^.{6,}$",
            },
        ),
        BrokerInfo(
            broker_id="tradier",
            name="Tradier",
            description="Brokerage API platform with competitive pricing. Good REST API.",
            api_type="rest",
            documentation_url="https://documentation.tradier.com",
            supports_paper_trading=True,
            supports_options=True,
            supports_futures=False,
            commission_model="zero_commission",
            credential_keys=["TRADIER_ACCESS_TOKEN", "TRADIER_ACCOUNT_ID"],
            validation_patterns={
                "TRADIER_ACCESS_TOKEN": r"^[A-Za-z0-9]{20,}$",
                "TRADIER_ACCOUNT_ID": r"^[A-Z0-9]{6,}$",
            },
        ),
        BrokerInfo(
            broker_id="td_ameritrade",
            name="Charles Schwab (TD Ameritrade)",
            description="Full-service broker with comprehensive API. Now under Schwab.",
            api_type="rest",
            documentation_url="https://developer.schwab.com",
            supports_paper_trading=True,
            supports_options=True,
            supports_futures=True,
            commission_model="zero_commission",
            credential_keys=["SCHWAB_APP_KEY", "SCHWAB_APP_SECRET", "SCHWAB_ACCOUNT_ID"],
            validation_patterns={
                "SCHWAB_APP_KEY": r"^.{10,}$",
                "SCHWAB_APP_SECRET": r"^.{10,}$",
                "SCHWAB_ACCOUNT_ID": r"^.{6,}$",
            },
        ),
    ],
    news_sources=[
        NewsSource(name="Yahoo Finance", url="https://feeds.finance.yahoo.com/rss/2.0/headline", category="general"),
        NewsSource(name="Reuters", url="https://www.reutersagency.com/feed/", category="general"),
        NewsSource(name="SEC EDGAR", url="https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&dateb=&owner=include&count=40&search_text=", category="regulatory"),
        NewsSource(name="Bloomberg", url="https://www.bloomberg.com/markets", category="general"),
        NewsSource(name="CNBC", url="https://www.cnbc.com/id/100003114/device/rss/rss.html", category="general"),
    ],
    data_suffix="",
    supports_short_selling=True,
    supports_options=True,
    supports_futures=True,
    supports_pre_market=True,
    supports_after_hours=True,
    min_lot_size=1,
    default_symbols=[
        "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA",
        "META", "TSLA", "BRK-B", "JPM", "V",
        "UNH", "MA", "HD", "PG", "JNJ",
        "AVGO", "XOM", "LLY", "COST", "ABBV",
    ],
    regulator="SEC (Securities and Exchange Commission)",
    regulator_url="https://www.sec.gov",
    filing_sources=["sec_edgar"],
)
