"""Market Profile — Pydantic models for multi-country market configuration.

Defines the complete schema for a market profile including trading hours,
tax rules, available brokers, news sources, and exchange-specific settings.
Each supported country has a pre-built profile that can be customized.

The MarketProfile is the single source of truth for all country-specific
behavior in the trading engine, RMS, and UI.
"""

from __future__ import annotations

from datetime import time
from enum import Enum

from pydantic import BaseModel, Field, field_validator

# ── Enums ───────────────────────────────────────────────────────────────────


class Country(str, Enum):
    """Supported countries for trading."""

    INDIA = "IN"
    UNITED_STATES = "US"
    UNITED_KINGDOM = "UK"
    AUSTRALIA = "AU"
    CANADA = "CA"
    GERMANY = "DE"
    JAPAN = "JP"
    SINGAPORE = "SG"
    HONG_KONG = "HK"
    BRAZIL = "BR"
    FRANCE = "FR"
    SOUTH_KOREA = "KR"
    NETHERLANDS = "NL"
    SWITZERLAND = "CH"
    SWEDEN = "SE"


class Exchange(str, Enum):
    """Supported stock exchanges."""

    # India
    NSE = "NSE"
    BSE = "BSE"
    # United States
    NYSE = "NYSE"
    NASDAQ = "NASDAQ"
    # United Kingdom
    LSE = "LSE"
    # Australia
    ASX = "ASX"
    # Canada
    TSX = "TSX"
    # Germany
    XETRA = "XETRA"
    FRA = "FRA"
    # Japan
    JPX = "JPX"
    TSE_JP = "TSE_JP"
    # Singapore
    SGX = "SGX"
    # Hong Kong
    HKEX = "HKEX"
    # Brazil
    B3 = "B3"
    # France
    EURONEXT_PARIS = "EURONEXT_PARIS"
    # South Korea
    KRX = "KRX"
    # Netherlands
    EURONEXT_AMS = "EURONEXT_AMS"
    # Switzerland
    SIX = "SIX"
    # Sweden
    OMX_STOCKHOLM = "OMX_STOCKHOLM"


class SettlementCycle(str, Enum):
    """Trade settlement cycles."""

    T0 = "T+0"
    T1 = "T+1"
    T2 = "T+2"
    T3 = "T+3"


class NumberFormat(str, Enum):
    """Number formatting conventions."""

    INDIAN = "indian"  # 1,00,000 (lakh/crore)
    INTERNATIONAL = "international"  # 100,000 (million/billion)
    EUROPEAN = "european"  # 100.000,00 (dot as thousands separator)


# ── Models ──────────────────────────────────────────────────────────────────


class MarketSession(BaseModel):
    """Trading session time boundaries for an exchange."""

    pre_market_start: time | None = None
    pre_market_end: time | None = None
    market_open: time
    trading_start: time = Field(
        description="Signal generation begins (after candle warmup)",
    )
    trading_end: time = Field(
        description="No new entries after this time",
    )
    square_off_time: time = Field(
        description="Force-close all intraday positions",
    )
    market_close: time
    post_market_start: time | None = None
    post_market_end: time | None = None

    @field_validator("trading_start")
    @classmethod
    def trading_start_after_open(cls, v: time, info) -> time:
        if "market_open" in info.data and v < info.data["market_open"]:
            raise ValueError("trading_start must be >= market_open")
        return v


class TaxRule(BaseModel):
    """A single tax or charge applied to trades.

    Represents transaction-level taxes like STT (India), stamp duty,
    exchange fees, SEC fees (US), etc.
    """

    name: str = Field(description="Human-readable tax name")
    rate_pct: float = Field(ge=0, le=100, description="Tax rate as percentage")
    applies_to: str = Field(
        description="When this tax applies: buy, sell, both, intraday, delivery, brokerage",
    )
    description: str = Field(description="Explanation of this tax")
    threshold: float | None = Field(
        default=None,
        description="Minimum trade value before this tax applies (in local currency)",
    )
    is_flat_fee: bool = Field(
        default=False,
        description="If True, rate_pct is ignored and threshold is the flat fee amount",
    )
    flat_fee_amount: float | None = Field(
        default=None,
        description="Flat fee amount in local currency (used when is_flat_fee=True)",
    )


class TaxProfile(BaseModel):
    """Complete tax configuration for a country's stock market.

    Generated by AI and verified by user. Used for charge estimation
    on order tickets — NOT for official tax filing.
    """

    country: Country
    currency: str = Field(description="ISO 4217 currency code")
    transaction_taxes: list[TaxRule] = Field(
        default_factory=list,
        description="All transaction-level taxes and charges",
    )
    capital_gains_short_term_pct: float = Field(
        ge=0, le=100,
        description="Short-term capital gains tax rate",
    )
    capital_gains_long_term_pct: float = Field(
        ge=0, le=100,
        description="Long-term capital gains tax rate",
    )
    short_term_threshold_days: int = Field(
        ge=0,
        description="Holding period (days) to qualify as long-term. 0 if no distinction.",
    )
    wash_sale_rule: bool = Field(
        default=False,
        description="Whether wash sale rules apply (e.g., US 30-day rule)",
    )
    wash_sale_window_days: int = Field(
        default=0, ge=0,
        description="Wash sale window in days (0 if not applicable)",
    )
    dividend_tax_pct: float = Field(
        default=0, ge=0, le=100,
        description="Tax on dividend income",
    )
    last_updated: str = Field(description="ISO date of last update")
    source: str = Field(
        description="How this profile was created: ai_generated, manual, official",
    )
    verified_by_user: bool = Field(
        default=False,
        description="Whether the user has reviewed and confirmed these rules",
    )
    disclaimer: str = Field(
        default="Tax estimates only. Consult a tax professional for filing.",
        description="Legal disclaimer shown to user",
    )


class BrokerInfo(BaseModel):
    """Information about a broker available in a specific country."""

    broker_id: str = Field(description="Internal identifier (e.g., 'shoonya', 'alpaca')")
    name: str = Field(description="Display name")
    description: str = Field(description="Brief description")
    api_type: str = Field(description="API protocol: rest, websocket, fix")
    documentation_url: str = Field(description="Link to API docs")
    supports_paper_trading: bool = Field(default=False)
    supports_options: bool = Field(default=False)
    supports_futures: bool = Field(default=False)
    commission_model: str = Field(
        default="per_trade",
        description="Commission structure: per_trade, per_share, zero_commission",
    )
    credential_keys: list[str] = Field(
        default_factory=list,
        description="Environment variable names needed for this broker",
    )
    validation_patterns: dict[str, str] = Field(
        default_factory=dict,
        description="Regex patterns for credential validation",
    )


class NewsSource(BaseModel):
    """A financial news source for sentiment analysis."""

    name: str
    url: str = Field(description="RSS feed URL or API endpoint")
    language: str = Field(default="en")
    category: str = Field(
        default="general",
        description="Category: general, earnings, regulatory, macro",
    )


class MarketProfile(BaseModel):
    """Complete market configuration for a country.

    This is the single source of truth for all country-specific behavior.
    Selected during setup wizard Step 1 and persisted to config/market.yaml.
    """

    country: Country
    country_name: str = Field(description="Full country name for display")
    currency: str = Field(description="ISO 4217 currency code (INR, USD, GBP, etc.)")
    currency_symbol: str = Field(description="Currency symbol for display (₹, $, £, etc.)")
    timezone: str = Field(description="IANA timezone (e.g., Asia/Kolkata, America/New_York)")
    number_format: NumberFormat = Field(default=NumberFormat.INTERNATIONAL)

    # Exchanges
    exchanges: list[Exchange] = Field(min_length=1)
    primary_exchange: Exchange

    # Benchmark index for volatility guard
    benchmark_index_name: str = Field(
        description="Human-readable name (e.g., 'Nifty 50', 'S&P 500')",
    )
    benchmark_symbol: str = Field(
        description="Symbol used in data feeds (e.g., '^NSEI', '^GSPC', '^FTSE')",
    )
    benchmark_redis_key: str = Field(
        description="Redis key prefix for benchmark price (e.g., 'nifty', 'sp500')",
    )

    # Trading sessions
    sessions: MarketSession

    # Settlement
    settlement_cycle: SettlementCycle = Field(default=SettlementCycle.T1)

    # Tax
    tax_profile: TaxProfile

    # Brokers available in this market
    available_brokers: list[BrokerInfo] = Field(default_factory=list)

    # News sources for sentiment analysis
    news_sources: list[NewsSource] = Field(default_factory=list)

    # Data provider settings
    data_suffix: str = Field(
        default="",
        description="yfinance suffix for this exchange (e.g., '.NS' for NSE, '' for US)",
    )

    # Market capabilities
    supports_short_selling: bool = Field(default=True)
    supports_options: bool = Field(default=True)
    supports_futures: bool = Field(default=True)
    supports_pre_market: bool = Field(default=False)
    supports_after_hours: bool = Field(default=False)
    min_lot_size: int = Field(default=1, ge=1)

    # Default symbols (popular stocks for this market)
    default_symbols: list[str] = Field(
        default_factory=list,
        description="Default watchlist symbols for this market",
    )

    # Regulatory body
    regulator: str = Field(
        default="",
        description="Financial regulator name (e.g., SEBI, SEC, FCA)",
    )
    regulator_url: str = Field(default="", description="Regulator website URL")

    # Filing/announcement sources for research
    filing_sources: list[str] = Field(
        default_factory=list,
        description="Sources for corporate filings (e.g., 'bse_feed', 'sec_edgar')",
    )
