"""
Strategy Engine for LOHI-TRADE.

Defines the abstract Strategy interface and Signal data structure for
trading signal generation. Concrete strategy implementations (Mean Reversion,
Trend Following, Opening Range Breakout) are added in subsequent tasks.

Requirements: 4.1, 4.5
"""

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Optional, Tuple

import pandas as pd

from src.soldier.indicator_engine import IndicatorSet
from src.utils.config import MeanReversionStrategy as MeanReversionConfig
from src.utils.config import OpeningRangeBreakoutStrategy as ORBConfig
from src.utils.config import TrendFollowingStrategy as TrendFollowingConfig
from src.utils.logger import get_logger

logger = get_logger("StrategyEngine")


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Contains all information needed for the RMS to validate and the OMS
    to execute a trade: entry price, stop loss, target, and a snapshot
    of the indicators at signal time.

    Attributes:
        signal_id: Unique identifier (UUID).
        symbol: Trading symbol (e.g., "RELIANCE").
        strategy: Name of the strategy that generated this signal.
        side: Trade direction, either 'BUY' or 'SELL'.
        entry_price: Suggested entry price.
        stop_loss: Stop-loss price (ATR-based).
        target: Target/take-profit price.
        quantity: Number of shares (calculated by Position Sizer, default 0).
        timestamp: When the signal was generated.
        indicators: Snapshot of indicators at signal time.
    """

    signal_id: str
    symbol: str
    strategy: str
    side: str  # 'BUY' or 'SELL'
    entry_price: float
    stop_loss: float
    target: float
    quantity: int
    timestamp: datetime
    indicators: IndicatorSet


def create_signal(
    symbol: str,
    strategy: str,
    side: str,
    entry_price: float,
    stop_loss: float,
    target: float,
    indicators: IndicatorSet,
    timestamp: Optional[datetime] = None,
) -> Signal:
    """
    Factory function to create a Signal with auto-generated ID and timestamp.

    Args:
        symbol: Trading symbol.
        strategy: Strategy name.
        side: 'BUY' or 'SELL'.
        entry_price: Entry price.
        stop_loss: Stop-loss price.
        target: Target price.
        indicators: Indicator snapshot.
        timestamp: Optional timestamp (defaults to now).

    Returns:
        A new Signal instance.

    Raises:
        ValueError: If side is not 'BUY' or 'SELL'.
    """
    if side not in ("BUY", "SELL"):
        raise ValueError(f"Invalid side '{side}', must be 'BUY' or 'SELL'")

    return Signal(
        signal_id=str(uuid.uuid4()),
        symbol=symbol,
        strategy=strategy,
        side=side,
        entry_price=entry_price,
        stop_loss=stop_loss,
        target=target,
        quantity=0,  # Will be set by Position Sizer
        timestamp=timestamp or datetime.now(),
        indicators=indicators,
    )


class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Each concrete strategy must implement `generate_signal`, which
    evaluates the current indicators and candle data to decide whether
    a trading signal should be produced.

    Strategies are stateless — all required context is passed via
    the method arguments.

    Requirements: 4.1
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the strategy name (e.g., 'MeanReversion')."""
        ...

    @property
    @abstractmethod
    def enabled(self) -> bool:
        """Whether this strategy is currently enabled in configuration."""
        ...

    @abstractmethod
    def generate_signal(
        self, indicators: IndicatorSet, candles: pd.DataFrame
    ) -> Optional[Signal]:
        """
        Evaluate indicators and candle data to generate a trading signal.

        Args:
            indicators: The latest calculated IndicatorSet for the symbol.
            candles: Recent candle DataFrame with columns:
                     open, high, low, close, volume, timestamp.

        Returns:
            A Signal if entry conditions are met, otherwise None.
        """
        ...

class MeanReversionStrategy(Strategy):
    """
    Mean Reversion strategy: generates BUY signals when price is
    oversold relative to Bollinger Bands and RSI, with volume
    confirmation and VWAP support.

    Entry conditions (all must be true):
        - RSI < rsi_oversold (default 30)
        - Price < BB lower band
        - Volume > volume_multiplier × 20-period average volume
        - Price > VWAP

    Stop Loss: entry_price - (stop_loss_atr_multiplier × ATR)
    Target: BB middle band

    Requirements: 4.2
    """

    def __init__(self, config: MeanReversionConfig) -> None:
        self._config = config

    @property
    def name(self) -> str:
        return "MeanReversion"

    @property
    def enabled(self) -> bool:
        return self._config.enabled

    def generate_signal(
        self, indicators: IndicatorSet, candles: pd.DataFrame
    ) -> Optional[Signal]:
        if not self._config.enabled:
            return None

        if candles.empty:
            return None

        entry_price = float(candles.iloc[-1]["close"])
        last_volume = float(candles.iloc[-1]["volume"])

        # Check all 4 entry conditions
        rsi_oversold = indicators.rsi_14 < self._config.rsi_oversold
        price_below_bb = entry_price < indicators.bb_lower
        volume_spike = last_volume > self._config.volume_multiplier * indicators.volume_avg_20
        price_above_vwap = entry_price > indicators.vwap

        if not (rsi_oversold and price_below_bb and volume_spike and price_above_vwap):
            return None

        stop_loss = entry_price - (self._config.stop_loss_atr_multiplier * indicators.atr_14)
        target = indicators.bb_middle

        logger.info(
            f"MeanReversion signal: symbol={indicators.symbol} "
            f"entry={entry_price:.2f} stop={stop_loss:.2f} "
            f"target={target:.2f} RSI={indicators.rsi_14:.1f}"
        )

        return create_signal(
            symbol=indicators.symbol,
            strategy=self.name,
            side="BUY",
            entry_price=entry_price,
            stop_loss=stop_loss,
            target=target,
            indicators=indicators,
        )


class TrendFollowingStrategy(Strategy):
    """
    Trend Following strategy: generates BUY signals when price is
    trending upward with momentum confirmation.

    Entry conditions (all must be true):
        - EMA(9) > EMA(21) (fast EMA above slow EMA)
        - MACD > 0
        - MACD histogram > 0 (MACD rising)
        - Price (last candle close) > VWAP
        - supertrend_direction == 1 (bullish)
        - Volume (last candle volume) > volume_avg_20

    Stop Loss: entry_price - (stop_loss_atr_multiplier × ATR)
    Target: entry_price + (target_atr_multiplier × ATR)

    Requirements: 4.3
    """

    def __init__(self, config: TrendFollowingConfig) -> None:
        self._config = config

    @property
    def name(self) -> str:
        return "TrendFollowing"

    @property
    def enabled(self) -> bool:
        return self._config.enabled

    def generate_signal(
        self, indicators: IndicatorSet, candles: pd.DataFrame
    ) -> Optional[Signal]:
        if not self._config.enabled:
            return None

        if candles.empty:
            return None

        entry_price = float(candles.iloc[-1]["close"])
        last_volume = float(candles.iloc[-1]["volume"])

        # Check all 6 entry conditions
        ema_crossover = indicators.ema_9 > indicators.ema_21
        macd_positive = indicators.macd > 0
        macd_rising = indicators.macd_hist > 0
        price_above_vwap = entry_price > indicators.vwap
        supertrend_bullish = indicators.supertrend_direction == 1
        volume_above_avg = last_volume > indicators.volume_avg_20

        if not (
            ema_crossover
            and macd_positive
            and macd_rising
            and price_above_vwap
            and supertrend_bullish
            and volume_above_avg
        ):
            return None

        stop_loss = entry_price - (self._config.stop_loss_atr_multiplier * indicators.atr_14)
        target = entry_price + (self._config.target_atr_multiplier * indicators.atr_14)

        logger.info(
            f"TrendFollowing signal: symbol={indicators.symbol} "
            f"entry={entry_price:.2f} stop={stop_loss:.2f} "
            f"target={target:.2f} EMA9={indicators.ema_9:.1f} EMA21={indicators.ema_21:.1f}"
        )

        return create_signal(
            symbol=indicators.symbol,
            strategy=self.name,
            side="BUY",
            entry_price=entry_price,
            stop_loss=stop_loss,
            target=target,
            indicators=indicators,
        )


class OpeningRangeBreakoutStrategy(Strategy):
    """
    Opening Range Breakout (ORB) strategy: generates BUY/SELL signals
    when price breaks above/below the opening range with volume confirmation.

    The opening range is the high/low from 9:15-9:30 AM, set externally
    via set_opening_range(). This strategy is stateful — it tracks the
    opening range per symbol.

    Entry conditions (during trade window, default 9:30-10:30 AM):
        - BUY: close > range_high AND volume > volume_multiplier × volume_avg_20
        - SELL: close < range_low AND volume > volume_multiplier × volume_avg_20

    Stop Loss: opposite end of opening range
    Target: entry_price ± (target_multiplier × range_size)

    Requirements: 4.4
    """

    def __init__(self, config: ORBConfig) -> None:
        self._config = config
        self._opening_ranges: Dict[str, Tuple[float, float]] = {}

    @property
    def name(self) -> str:
        return "OpeningRangeBreakout"

    @property
    def enabled(self) -> bool:
        return self._config.enabled

    def set_opening_range(self, symbol: str, range_high: float, range_low: float) -> None:
        """Set the opening range (high, low) for a symbol."""
        self._opening_ranges[symbol] = (range_high, range_low)

    def get_opening_range(self, symbol: str) -> Optional[Tuple[float, float]]:
        """Get the opening range for a symbol, or None if not set."""
        return self._opening_ranges.get(symbol)

    def clear_opening_ranges(self) -> None:
        """Reset all opening ranges (call at start of each trading day)."""
        self._opening_ranges.clear()

    def generate_signal(
        self, indicators: IndicatorSet, candles: pd.DataFrame
    ) -> Optional[Signal]:
        if not self._config.enabled:
            return None

        if candles.empty:
            return None

        symbol = indicators.symbol
        opening_range = self._opening_ranges.get(symbol)
        if opening_range is None:
            return None

        range_high, range_low = opening_range
        range_size = range_high - range_low

        last_candle = candles.iloc[-1]
        entry_price = float(last_candle["close"])
        last_volume = float(last_candle["volume"])
        candle_time = last_candle["timestamp"]

        # Parse trade window from config
        tw_start_parts = self._config.trade_window_start.split(":")
        tw_end_parts = self._config.trade_window_end.split(":")
        tw_start_hour, tw_start_min = int(tw_start_parts[0]), int(tw_start_parts[1])
        tw_end_hour, tw_end_min = int(tw_end_parts[0]), int(tw_end_parts[1])

        candle_total_minutes = candle_time.hour * 60 + candle_time.minute
        tw_start_total = tw_start_hour * 60 + tw_start_min
        tw_end_total = tw_end_hour * 60 + tw_end_min

        if not (tw_start_total <= candle_total_minutes <= tw_end_total):
            return None

        # Check volume condition
        volume_threshold = self._config.volume_multiplier * indicators.volume_avg_20
        if last_volume <= volume_threshold:
            return None

        # Check breakout direction
        side: Optional[str] = None
        stop_loss = 0.0
        target = 0.0

        if entry_price > range_high:
            side = "BUY"
            stop_loss = range_low
            target = entry_price + (self._config.target_multiplier * range_size)
        elif entry_price < range_low:
            side = "SELL"
            stop_loss = range_high
            target = entry_price - (self._config.target_multiplier * range_size)

        if side is None:
            return None

        logger.info(
            f"ORB signal: symbol={symbol} side={side} "
            f"entry={entry_price:.2f} stop={stop_loss:.2f} "
            f"target={target:.2f} range=({range_low:.2f}-{range_high:.2f})"
        )

        return create_signal(
            symbol=symbol,
            strategy=self.name,
            side=side,
            entry_price=entry_price,
            stop_loss=stop_loss,
            target=target,
            indicators=indicators,
        )

