"""Data Loss Prevention (DLP) safety layer for the research pipeline.

This module provides hard-coded, non-configurable safety checks that
protect against accidental or malicious data destruction. Unlike the
YAML-driven guardrail rules (which an operator could theoretically
modify), these checks are embedded in Python and cannot be bypassed
without changing source code.

Design principles:
    1. **Defense in depth** — even if guardrail rules are misconfigured,
       these checks still fire.
    2. **Fail closed** — any ambiguity results in a refusal.
    3. **Audit everything** — every blocked operation is logged with full
       context for forensic review.
    4. **Immutable backups** — backup paths are never writable by the
       LLM pipeline, only by the scheduled backup manager.
    5. **Bulk-delete protection** — operations affecting >N rows require
       explicit confirmation (not available to LLM agents).

Requirements: Req 4.8, Req 4.9, Req 9.3
Design: §14 (security), §3.6 (guardrails)
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Final

logger = logging.getLogger(__name__)


# ── Constants ───────────────────────────────────────────────────────────────

# Maximum rows a single forget/delete operation can affect without
# requiring elevated confirmation. LLM agents never have elevated
# confirmation, so this is effectively a hard cap on agent-initiated
# deletions.
MAX_BULK_DELETE_ROWS: Final[int] = 10_000

# Paths that must NEVER be writable by the research pipeline.
# These are checked at startup and on every write attempt.
PROTECTED_PATHS: Final[tuple[str, ...]] = (
    "data/backups",
    "data/backups/",
    ".env",
    ".env.research",
    "config/settings.yaml",
    "backend-gateway/.env",
)

# SQL keywords that must NEVER appear in any query generated by or
# influenced by LLM output. These are checked at the query-execution
# boundary, not just at the prompt level.
FORBIDDEN_SQL_KEYWORDS: Final[tuple[str, ...]] = (
    "DROP TABLE",
    "DROP DATABASE",
    "DROP SCHEMA",
    "TRUNCATE",
    "ALTER TABLE",
    "CREATE USER",
    "GRANT",
    "REVOKE",
)


# ── Safety checks ──────────────────────────────────────────────────────────


class DataSafetyViolation(Exception):
    """Raised when a data-safety check fails.

    Carries structured context for audit logging.
    """

    def __init__(self, check: str, detail: str, context: dict | None = None):
        self.check = check
        self.detail = detail
        self.context = context or {}
        super().__init__(f"[{check}] {detail}")


def check_path_not_protected(path: str | Path) -> None:
    """Raise if the given path is in the protected set.

    Called before any file-write operation in the research pipeline.
    """
    path_str = str(path)
    for protected in PROTECTED_PATHS:
        if path_str.endswith(protected) or protected in path_str:
            logger.critical(
                "DATA SAFETY: blocked write to protected path %s (matched %s)",
                path_str, protected,
            )
            raise DataSafetyViolation(
                check="PROTECTED_PATH",
                detail=f"Write to '{path_str}' is blocked — this path is protected.",
                context={"path": path_str, "matched_rule": protected},
            )


def check_bulk_delete_limit(row_count: int, scope: str) -> None:
    """Raise if a delete operation would affect too many rows.

    This is the last line of defense against runaway deletions.
    The memory.forget() function calls this before executing.
    """
    if row_count > MAX_BULK_DELETE_ROWS:
        logger.critical(
            "DATA SAFETY: blocked bulk delete of %d rows (scope=%s, limit=%d)",
            row_count, scope, MAX_BULK_DELETE_ROWS,
        )
        raise DataSafetyViolation(
            check="BULK_DELETE_LIMIT",
            detail=(
                f"Delete operation would affect {row_count} rows "
                f"(scope='{scope}'), exceeding the safety limit of "
                f"{MAX_BULK_DELETE_ROWS}. This operation requires manual "
                f"confirmation via the admin CLI."
            ),
            context={"row_count": row_count, "scope": scope, "limit": MAX_BULK_DELETE_ROWS},
        )


def check_sql_safety(query: str) -> None:
    """Raise if a SQL query contains forbidden destructive keywords.

    Called at the query-execution boundary for any query that was
    influenced by LLM output (e.g., dynamic filters). Queries from
    static application code (migrations, schema setup) bypass this
    check via a separate code path.
    """
    query_upper = query.upper()
    for keyword in FORBIDDEN_SQL_KEYWORDS:
        if keyword in query_upper:
            logger.critical(
                "DATA SAFETY: blocked SQL containing '%s' — query: %.200s",
                keyword, query,
            )
            raise DataSafetyViolation(
                check="FORBIDDEN_SQL",
                detail=f"Query contains forbidden keyword '{keyword}'.",
                context={"keyword": keyword, "query_preview": query[:200]},
            )


def check_backup_integrity() -> dict:
    """Verify backup directory exists and contains recent backups.

    Returns a health-check dict suitable for the /health endpoint.
    Called during startup and periodically by the health monitor.
    """
    backup_dir = Path("data/backups")
    result = {
        "backup_dir_exists": backup_dir.exists(),
        "backup_count": 0,
        "latest_backup": None,
        "status": "unknown",
    }

    if not backup_dir.exists():
        result["status"] = "missing"
        logger.warning("DATA SAFETY: backup directory does not exist at %s", backup_dir)
        return result

    backups = sorted(backup_dir.glob("*.db"), key=os.path.getmtime, reverse=True)
    result["backup_count"] = len(backups)

    if backups:
        latest = backups[0]
        result["latest_backup"] = latest.name
        # Check if latest backup is less than 48 hours old
        import time
        age_hours = (time.time() - os.path.getmtime(latest)) / 3600
        if age_hours > 48:
            result["status"] = "stale"
            logger.warning(
                "DATA SAFETY: latest backup is %.1f hours old (>48h threshold): %s",
                age_hours, latest.name,
            )
        else:
            result["status"] = "healthy"
    else:
        result["status"] = "empty"
        logger.warning("DATA SAFETY: backup directory exists but contains no .db files")

    return result


def startup_safety_checks() -> list[str]:
    """Run all startup-time safety checks.

    Returns a list of warning messages (empty = all clear).
    Called once during gateway/worker startup.
    """
    warnings: list[str] = []

    # 1. Verify backup directory
    backup_status = check_backup_integrity()
    if backup_status["status"] != "healthy":
        warnings.append(
            f"Backup status: {backup_status['status']} "
            f"(count={backup_status['backup_count']}, "
            f"latest={backup_status['latest_backup']})",
        )

    # 2. Verify protected paths are not world-writable
    for protected in PROTECTED_PATHS:
        p = Path(protected)
        if p.exists():
            mode = oct(p.stat().st_mode)[-3:]
            if mode.endswith("7") or mode.endswith("6"):
                msg = f"Protected path '{protected}' has permissive mode {mode}"
                warnings.append(msg)
                logger.warning("DATA SAFETY: %s", msg)

    # 3. Verify data directories exist
    for data_dir in ("data/research/chroma", "data/research/uploads", "data/research/snapshots"):
        if not Path(data_dir).exists():
            Path(data_dir).mkdir(parents=True, exist_ok=True)
            logger.info("DATA SAFETY: created missing directory %s", data_dir)

    if warnings:
        logger.warning("DATA SAFETY: %d startup warnings: %s", len(warnings), warnings)
    else:
        logger.info("DATA SAFETY: all startup checks passed")

    return warnings
